### ISSUE TITLE
Add a section for open source xna/monogame games

### ISSUE THREAD

**Issue by JamesC01** [UnterrainerInformatik/GameDevelopmentLinks#5]
I think it would be nice to have a section that has some good open source monogame/xna games, particularly good examples of code, not some random game posted to github, something more reputable. Not example code. Actual, complete games, big or small.

One example I can think of right now would be infiniminer.

**Comment by guFalcon** [comment]
That's a good idea.
Do you have such links? Because I personally don't. At least not from the top of my head.
But if you do happen to have such links, add them please and I will accept the PR of course.

**Comment by JamesC01** [comment]
https://github.com/craftworkgames/infiniminer I'm not sure of any other games, though.

**Comment by guFalcon** [comment]
Nice. Thx.
Added it.
