### ISSUE TITLE
The link for "Using shaders" is not working anymore...

### ISSUE THREAD

**Issue by FireDragonGameStudio** [UnterrainerInformatik/GameDevelopmentLinks#8]
... due to the shutdown of xnamag. But maybe ou can add a link to [https://thebookofshaders.com/](https://thebookofshaders.com/) instead, as this is imho also a good starting point for writing shaders.

Best regards :)

**Comment by guFalcon** [comment]
Thx for paying attention :)
I added the link you provided instead. Nice site. Thx.
